package ca.jrvs.apps.grep;

import ca.jrvs.apps.practice.RegexExcImp;

public class RegexExcImpTester {
    public static void main(String[] args) {
        RegexExcImp test = new RegexExcImp();
        System.out.println(test.matchJpeg("a.jpg"));
        System.out.println(test.matchJpeg("a.jpeg"));
        System.out.println(test.matchJpeg("_.jpg"));
        System.out.println(test.matchJpeg("_.jpeg"));
        System.out.println(test.matchJpeg("A.jpg"));
        System.out.println(test.matchJpeg("A.jpeg"));
        System.out.println(test.matchJpeg("1.jpg"));
        System.out.println(test.matchJpeg("1.jpeg"));
        System.out.println(test.matchJpeg("a.jPG"));
        System.out.println(test.matchJpeg("a.jPEG"));
        System.out.println(test.matchJpeg("_.Jpg"));
        System.out.println(test.matchJpeg("_.Jpeg"));
        System.out.println(test.matchJpeg("A.JpG"));
        System.out.println(test.matchJpeg("A.JpEG"));
        System.out.println(test.matchJpeg("__.Jpg"));
        System.out.println(test.matchJpeg("__.Jpeg"));
        System.out.println(test.matchJpeg("Abc.JpG"));
        System.out.println(test.matchJpeg("Abc.JpEG"));
        System.out.println(test.matchJpeg("123.JPG"));
        System.out.println(test.matchJpeg("123.JPEG"));
        System.out.println("-------------------------------");
        System.out.println(test.matchJpeg(".jpg"));
        System.out.println(test.matchJpeg(".jpeg"));
        System.out.println(test.matchJpeg(".jpG"));
        System.out.println(test.matchJpeg(".jpeG"));
        System.out.println(test.matchJpeg(" .jpg"));
        System.out.println(test.matchJpeg(" .jpeg"));
        System.out.println(test.matchJpeg(" jpg"));
        System.out.println(test.matchJpeg(" jpeg"));
        System.out.println(test.matchJpeg("1 jpg"));
        System.out.println(test.matchJpeg("1 jpeg"));
        System.out.println(test.matchJpeg("a jpg"));
        System.out.println(test.matchJpeg("a jpeg"));
        System.out.println(test.matchJpeg("A jpg"));
        System.out.println(test.matchJpeg("A jpeg"));
        System.out.println(test.matchJpeg("_ jpg"));
        System.out.println(test.matchJpeg("_ jpeg"));
        System.out.println(test.matchJpeg("1.jpg1"));
        System.out.println(test.matchJpeg("1.jpeg1"));
        System.out.println(test.matchJpeg("1.jpg "));
        System.out.println(test.matchJpeg("1.jpeg "));
        System.out.println(test.matchJpeg("1.jpg?"));
        System.out.println(test.matchJpeg("1.jpeg?"));
        System.out.println(test.matchJpeg("1.jpgg"));
        System.out.println(test.matchJpeg("1.jpegg"));
        System.out.println(test.matchJpeg(" .jpg"));
        System.out.println(test.matchJpeg(" .jpeg"));
        System.out.println(test.matchJpeg(" jpg"));
        System.out.println(test.matchJpeg(" jpeg"));
        System.out.println(test.matchJpeg("1 jpg"));
        System.out.println(test.matchJpeg("1 jpeg"));
        System.out.println(test.matchJpeg("a jpg"));
        System.out.println(test.matchJpeg("a jpeg"));
        System.out.println(test.matchJpeg("A jpg"));
        System.out.println(test.matchJpeg("A jpeg"));
        System.out.println(test.matchJpeg("_ jpg"));
        System.out.println(test.matchJpeg("_ jpeg"));
        System.out.println("-------------------------------");
        System.out.println(test.matchIp("0.0.0.0"));
        System.out.println(test.matchIp("1.01.001.011"));
        System.out.println(test.matchIp("011.001.01.1"));
        System.out.println(test.matchIp("000.000.000.000"));
        System.out.println("-------------------------------");
        System.out.println(test.matchIp("1A0.001.001.011"));
        System.out.println(test.matchIp("011.001.0_1.111"));
        System.out.println(test.matchIp("000.000.000.000.000"));
        System.out.println(test.matchIp("1.1.1.1."));
        System.out.println("-------------------------------");
        System.out.println(test.isEmptyLine(""));
        System.out.println(test.isEmptyLine(" "));
        System.out.println(test.isEmptyLine("\t"));
        System.out.println(test.isEmptyLine("\n"));
    }
}
